# Generated by Django 3.0 on 2019-12-07 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
        migrations.AddField(
            model_name='user',
            name='favorite_station1',
            field=models.CharField(blank=True, choices=[('LAKE', 'Lake Merritt'), ('FTVL', 'Fruitvale'), ('COLS', 'Coliseum'), ('SANL', 'San Leandro'), ('BAYF', 'Bay Fair'), ('HAYW', 'Hayward'), ('SHAY', 'South Hayward'), ('UCTY', 'Union City'), ('FRMT', 'Fremont'), ('ROCK', 'Rockridge'), ('ORIN', 'Orinda'), ('LAFY', 'Lafayette'), ('WCRK', 'Walnut Creek'), ('PHIL', 'Pleasant Hill/Contra Costa Centre'), ('CONC', 'Concord'), ('NCON', 'North Concord/Martinez'), ('PITT', 'Pittsburg/Bay Point'), ('PCTR', 'Pittsburg Center'), ('ANTC', 'Antioch'), ('12TH', '12th St. Oakland City Center'), ('19TH', '19th St. Oakland'), ('MCAR', 'MacArthur'), ('CAST', 'Castro Valley'), ('WDUB', 'West Dublin/Pleasanton'), ('DUBL', 'Dublin/Pleasanton'), ('WOAK', 'West Oakland'), ('EMBR', 'Embarcadero'), ('MONT', 'Montgomery St.'), ('POWL', 'Powell St.'), ('CIVC', 'Civic Center/UN Plaza'), ('16TH', '16th St. Mission'), ('24TH', '24th St. Mission'), ('GLEN', 'Glen Park'), ('BALB', 'Balboa Park'), ('DALY', 'Daly City'), ('ASHB', 'Ashby'), ('DBRK', 'Downtown Berkeley'), ('NBRK', 'North Berkeley'), ('PLZA', 'El Cerrito Plaza'), ('DELN', 'El Cerrito del Norte'), ('RICH', 'Richmond'), ('WARM', 'Warm Springs/South Fremont'), ('COLM', 'Colma'), ('SSAN', 'South San Francisco'), ('SBRN', 'San Bruno'), ('MLBR', 'Millbrae'), ('SFIA', "San Francisco Int'l Airport")], max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='favorite_station2',
            field=models.CharField(blank=True, choices=[('LAKE', 'Lake Merritt'), ('FTVL', 'Fruitvale'), ('COLS', 'Coliseum'), ('SANL', 'San Leandro'), ('BAYF', 'Bay Fair'), ('HAYW', 'Hayward'), ('SHAY', 'South Hayward'), ('UCTY', 'Union City'), ('FRMT', 'Fremont'), ('ROCK', 'Rockridge'), ('ORIN', 'Orinda'), ('LAFY', 'Lafayette'), ('WCRK', 'Walnut Creek'), ('PHIL', 'Pleasant Hill/Contra Costa Centre'), ('CONC', 'Concord'), ('NCON', 'North Concord/Martinez'), ('PITT', 'Pittsburg/Bay Point'), ('PCTR', 'Pittsburg Center'), ('ANTC', 'Antioch'), ('12TH', '12th St. Oakland City Center'), ('19TH', '19th St. Oakland'), ('MCAR', 'MacArthur'), ('CAST', 'Castro Valley'), ('WDUB', 'West Dublin/Pleasanton'), ('DUBL', 'Dublin/Pleasanton'), ('WOAK', 'West Oakland'), ('EMBR', 'Embarcadero'), ('MONT', 'Montgomery St.'), ('POWL', 'Powell St.'), ('CIVC', 'Civic Center/UN Plaza'), ('16TH', '16th St. Mission'), ('24TH', '24th St. Mission'), ('GLEN', 'Glen Park'), ('BALB', 'Balboa Park'), ('DALY', 'Daly City'), ('ASHB', 'Ashby'), ('DBRK', 'Downtown Berkeley'), ('NBRK', 'North Berkeley'), ('PLZA', 'El Cerrito Plaza'), ('DELN', 'El Cerrito del Norte'), ('RICH', 'Richmond'), ('WARM', 'Warm Springs/South Fremont'), ('COLM', 'Colma'), ('SSAN', 'South San Francisco'), ('SBRN', 'San Bruno'), ('MLBR', 'Millbrae'), ('SFIA', "San Francisco Int'l Airport")], max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='favorite_station3',
            field=models.CharField(blank=True, choices=[('LAKE', 'Lake Merritt'), ('FTVL', 'Fruitvale'), ('COLS', 'Coliseum'), ('SANL', 'San Leandro'), ('BAYF', 'Bay Fair'), ('HAYW', 'Hayward'), ('SHAY', 'South Hayward'), ('UCTY', 'Union City'), ('FRMT', 'Fremont'), ('ROCK', 'Rockridge'), ('ORIN', 'Orinda'), ('LAFY', 'Lafayette'), ('WCRK', 'Walnut Creek'), ('PHIL', 'Pleasant Hill/Contra Costa Centre'), ('CONC', 'Concord'), ('NCON', 'North Concord/Martinez'), ('PITT', 'Pittsburg/Bay Point'), ('PCTR', 'Pittsburg Center'), ('ANTC', 'Antioch'), ('12TH', '12th St. Oakland City Center'), ('19TH', '19th St. Oakland'), ('MCAR', 'MacArthur'), ('CAST', 'Castro Valley'), ('WDUB', 'West Dublin/Pleasanton'), ('DUBL', 'Dublin/Pleasanton'), ('WOAK', 'West Oakland'), ('EMBR', 'Embarcadero'), ('MONT', 'Montgomery St.'), ('POWL', 'Powell St.'), ('CIVC', 'Civic Center/UN Plaza'), ('16TH', '16th St. Mission'), ('24TH', '24th St. Mission'), ('GLEN', 'Glen Park'), ('BALB', 'Balboa Park'), ('DALY', 'Daly City'), ('ASHB', 'Ashby'), ('DBRK', 'Downtown Berkeley'), ('NBRK', 'North Berkeley'), ('PLZA', 'El Cerrito Plaza'), ('DELN', 'El Cerrito del Norte'), ('RICH', 'Richmond'), ('WARM', 'Warm Springs/South Fremont'), ('COLM', 'Colma'), ('SSAN', 'South San Francisco'), ('SBRN', 'San Bruno'), ('MLBR', 'Millbrae'), ('SFIA', "San Francisco Int'l Airport")], max_length=30),
        ),
    ]
