# Generated by Django 3.0 on 2019-12-07 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StationArrival',
        ),
    ]
